import React from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useQuery } from '@tanstack/react-query';
import { Header } from '../../src/components/Header';
import { api } from '../../src/services/api';

export default function Screen() {
  const { data, isLoading, isError } = useQuery({ queryKey: ['student-auto-timetable'], queryFn: async () => (await api.get('/timetable')).data });
  return <View style={s.page}><Header title="Student portal"/><ScrollView contentContainerStyle={s.content}>
    <View style={s.hero}><Text style={s.eyebrow}>AUTO-GENERATED DAILY TIMETABLE</Text><Text style={s.title}>Today’s Schedule</Text><Text style={s.date}>{data?.dayName ? `${data.dayName}, ${data.date}` : 'Current date'}</Text><Text style={s.meta}>{data?.className ? `Class ${data.className} • Section ${data.sectionName}` : 'Your academic schedule'}</Text></View>
    {isLoading ? <View style={s.state}><ActivityIndicator color="#C88728"/><Text style={s.stateText}>Loading your academic timetable…</Text></View> : isError ? <View style={s.state}><Text style={s.error}>Timetable could not be loaded.</Text></View> : <View style={s.list}>{(data?.periods || []).map((period: any) => <View key={period.periodNumber} style={s.period}><View style={s.time}><Text style={s.periodNo}>P{period.periodNumber}</Text><Text style={s.timeText}>{period.startTime}–{period.endTime}</Text></View><View style={s.subject}><Text style={s.subjectName}>{period.subject.name}</Text><Text style={s.teacher}>{period.teacher?.name || 'Teacher not assigned'}</Text></View><View style={[s.badge, period.status === 'CLASS_WORK' && s.workBadge]}><Text style={[s.badgeText, period.status === 'CLASS_WORK' && s.workText]}>{period.status === 'CLASS_WORK' ? 'CLASS WORK' : 'SCHEDULED'}</Text></View></View>)}</View>}
    {!isLoading && !isError && !(data?.periods || []).length ? <View style={s.state}><Text style={s.stateText}>No academic subjects are available yet.</Text></View> : null}
  </ScrollView></View>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#F4F1EA'},content:{padding:20,paddingBottom:50,maxWidth:1100,width:'100%',alignSelf:'center'},hero:{backgroundColor:'#0B2743',padding:26,borderRadius:22,marginBottom:18},eyebrow:{color:'#E6A84A',fontSize:11,fontWeight:'800',letterSpacing:2},title:{color:'#fff',fontSize:28,fontWeight:'800',marginTop:8},date:{color:'#fff',fontSize:18,fontWeight:'700',marginTop:10},meta:{color:'#B8CFDB',fontSize:13,marginTop:6},list:{gap:10},period:{backgroundColor:'#fff',borderRadius:16,padding:16,flexDirection:'row',alignItems:'center',gap:14,borderWidth:1,borderColor:'#E1DDD4'},time:{width:125},periodNo:{color:'#A66B1F',fontSize:11,fontWeight:'800'},timeText:{color:'#60758A',fontSize:12,marginTop:4},subject:{flex:1},subjectName:{color:'#17324D',fontSize:16,fontWeight:'800'},teacher:{color:'#718096',fontSize:13,marginTop:5},badge:{backgroundColor:'#EAF4EF',borderRadius:20,paddingHorizontal:10,paddingVertical:6},badgeText:{color:'#287A54',fontSize:10,fontWeight:'800'},workBadge:{backgroundColor:'#FFF4DD'},workText:{color:'#A66B1F'},state:{backgroundColor:'#fff',borderRadius:18,padding:40,alignItems:'center'},stateText:{color:'#718096',fontSize:13,marginTop:10,textAlign:'center'},error:{color:'#B42318',fontWeight:'700'}});
