import React, { useMemo, useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useQuery } from '@tanstack/react-query';
import { Header } from './Header';
import { api } from '../services/api';

const monthNames = ['January','February','March','April','May','June','July','August','September','October','November','December'];
const dayNames = ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];
const dayColor: Record<string, string> = { HOLIDAY: '#B42318', WEEKLY_OFF: '#7A5A16', WORKING_DAY: '#287A54' };

export function AcademicCalendarScreen({ role }: { role: 'student' | 'employee' }) {
  const now = new Date();
  const [month, setMonth] = useState(new Date(now.getFullYear(), now.getMonth(), 1));
  const { data = [], isLoading, isError } = useQuery<any[]>({ queryKey: ['academic-calendar'], queryFn: async () => (await api.get('/academics/calendar')).data });
  const entries = useMemo(() => data.filter((entry: any) => { const date = new Date(entry.date); return date.getFullYear() === month.getFullYear() && date.getMonth() === month.getMonth(); }), [data, month]);
  const calendarEntries = useMemo(() => { const result = new Map(entries.map((entry: any) => [new Date(entry.date).getDate(), entry])); const days = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate(); for (let day = 1; day <= days; day += 1) { if (new Date(month.getFullYear(), month.getMonth(), day).getDay() === 0) result.set(day, { id: `sunday-${month.getFullYear()}-${month.getMonth()}-${day}`, date: new Date(month.getFullYear(), month.getMonth(), day), dayType: 'WEEKLY_OFF', title: 'Sunday holiday' }); } return Array.from(result.values()).sort((a: any, b: any) => new Date(a.date).getTime() - new Date(b.date).getTime()); }, [entries, month]);
  const byDate = useMemo(() => new Map(calendarEntries.map((entry: any) => [new Date(entry.date).getDate(), entry])), [calendarEntries]);
  const cells = useMemo(() => { const first = new Date(month.getFullYear(), month.getMonth(), 1).getDay(); const count = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate(); return [...Array(first).fill(null), ...Array.from({ length: count }, (_, index) => index + 1)]; }, [month]);
  return <View style={s.page}><Header title={`${role === 'student' ? 'Student' : 'Employee'} portal`} /><ScrollView contentContainerStyle={s.content}><View style={s.hero}><Text style={s.eyebrow}>ACADEMIC CALENDAR</Text><Text style={s.title}>School Calendar</Text><Text style={s.subtitle}>Official holidays, weekly offs and academic dates published by administration.</Text></View><View style={s.calendar}><View style={s.monthBar}><TouchableOpacity accessibilityRole="button" onPress={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))}><Text style={s.arrow}>‹</Text></TouchableOpacity><Text style={s.month}>{monthNames[month.getMonth()]} {month.getFullYear()}</Text><TouchableOpacity accessibilityRole="button" onPress={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))}><Text style={s.arrow}>›</Text></TouchableOpacity></View><View style={s.week}>{dayNames.map((day) => <Text key={day} style={s.weekDay}>{day}</Text>)}</View>{isLoading ? <View style={s.state}><ActivityIndicator color="#C88728"/><Text style={s.muted}>Loading academic calendar…</Text></View> : isError ? <View style={s.state}><Text style={s.error}>Calendar could not be loaded.</Text></View> : <View style={s.grid}>{cells.map((day, index) => { const entry = day ? byDate.get(day) : null; return <View key={`${month.getMonth()}-${index}`} style={[s.cell, !day && s.blank, entry && { borderColor: dayColor[entry.dayType] || '#C88728' }]}>{day ? <><Text style={s.date}>{day}</Text>{entry ? <><View style={[s.dot, { backgroundColor: dayColor[entry.dayType] || '#C88728' }]} /><Text numberOfLines={2} style={s.event}>{entry.title || entry.dayType.replace('_', ' ')}</Text></> : null}</> : null}</View>; })}</View>}<View style={s.legend}><Text style={s.legendTitle}>Calendar details</Text>{calendarEntries.length ? calendarEntries.map((entry: any) => <View key={entry.id} style={s.detail}><View style={[s.dot, { backgroundColor: dayColor[entry.dayType] || '#C88728' }]} /><Text style={s.detailText}>{new Date(entry.date).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' })} · {entry.title || entry.dayType.replace('_', ' ')}</Text></View>) : <Text style={s.muted}>No administration-published dates for this month.</Text>}</View></View></ScrollView></View>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#F4F1EA'},content:{padding:20,paddingBottom:50,maxWidth:1050,width:'100%',alignSelf:'center'},hero:{backgroundColor:'#0B2743',padding:26,borderRadius:22,marginBottom:18},eyebrow:{color:'#E6A84A',fontSize:11,fontWeight:'800',letterSpacing:2},title:{color:'#fff',fontSize:28,fontWeight:'800',marginTop:8},subtitle:{color:'#B8CFDB',fontSize:13,marginTop:7},calendar:{backgroundColor:'#fff',borderRadius:18,padding:18,borderWidth:1,borderColor:'#E1DDD4'},monthBar:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:18},arrow:{fontSize:34,color:'#A66B1F',paddingHorizontal:14},month:{fontSize:21,fontWeight:'800',color:'#17324D'},week:{flexDirection:'row',marginBottom:8},weekDay:{flex:1,textAlign:'center',fontSize:11,fontWeight:'800',color:'#718096'},grid:{flexDirection:'row',flexWrap:'wrap'},cell:{width:'14.2857%',minHeight:82,borderWidth:1,borderColor:'#EEEAE3',padding:7,backgroundColor:'#FFFEFC'},blank:{backgroundColor:'#F8F6F1'},date:{color:'#17324D',fontSize:13,fontWeight:'800'},dot:{width:8,height:8,borderRadius:4,marginTop:8},event:{color:'#60758A',fontSize:10,lineHeight:13,marginTop:4},legend:{borderTopWidth:1,borderTopColor:'#EEEAE3',marginTop:18,paddingTop:16},legendTitle:{color:'#17324D',fontSize:15,fontWeight:'800',marginBottom:10},detail:{flexDirection:'row',alignItems:'center',gap:8,marginTop:7},detailText:{color:'#60758A',fontSize:13},state:{padding:30,alignItems:'center'},muted:{color:'#718096',fontSize:13,marginTop:8},error:{color:'#B42318',fontWeight:'700'}});
