import React from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useQuery } from '@tanstack/react-query';
import { Header } from './Header';
import { AdminNav } from './AdminNav';
import { api } from '../services/api';
type Props = { title:string; eyebrow:string; description:string; endpoint:string; admin?:boolean; actionLabel?:string };
export function PortalModuleScreen({title,eyebrow,description,endpoint,admin=false}:Props){
 const {data,isLoading,isError,refetch}=useQuery({queryKey:['module',endpoint],queryFn:async()=>(await api.get(endpoint)).data});
 const rows=Array.isArray(data)?data:data?Object.entries(data).filter(([,value])=>Array.isArray(value)).flatMap(([,value])=>value as any[]):[];
 const emptyMessage = endpoint.includes('attendance') ? 'No attendance records are available for your account yet.' : endpoint.includes('fees') ? 'No fee account or payment information is available yet.' : endpoint.includes('results') || endpoint.includes('assessments') ? 'No published academic results are available yet.' : endpoint.includes('notices') ? 'No notices have been published for you yet.' : endpoint.includes('timetable') ? 'No academic periods are available for your class yet.' : 'No school records are available yet.';
 return <View style={s.page}><Header title={title}/>{admin?<AdminNav/>:null}<ScrollView contentContainerStyle={s.content}><View style={s.hero}><View style={s.heroCopy}><Text style={s.eyebrow}>{eyebrow}</Text><Text style={s.title}>{title}</Text><Text style={s.description}>{description}</Text></View>{admin?<TouchableOpacity accessibilityRole="button" style={s.action} onPress={()=>refetch()}><Text style={s.actionText}>↻ Refresh data</Text></TouchableOpacity>:null}</View>{isLoading?<View style={s.state}><ActivityIndicator color="#C88728"/><Text style={s.stateText}>Loading verified school records…</Text></View>:isError?<View style={s.state}><Text style={s.error}>Records could not be loaded.</Text><TouchableOpacity onPress={()=>refetch()}><Text style={s.retry}>Try again</Text></TouchableOpacity></View>:rows.length===0?<View style={s.state}><Text style={s.emptyIcon}>◇</Text><Text style={s.stateTitle}>No records available</Text><Text style={s.stateText}>{emptyMessage}</Text></View>:<View style={s.grid}>{rows.slice(0,50).map((row:any,index:number)=><View style={s.card} key={row.id||index}><View style={s.cardTop}><Text style={s.cardTitle}>{String(row.title||row.name||row.studentId||row.employeeId||`Record ${index+1}`)}</Text><View style={s.badge}><Text style={s.badgeText}>{String(row.status||row.type||'ACTIVE').split('_').join(' ')}</Text></View></View><Text numberOfLines={3} style={s.cardBody}>{String(row.message||row.designation||row.description||row.academicYear?.name||'Additional details are not available.')}</Text></View>)}</View>}</ScrollView></View>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#F4F1EA'},content:{padding:20,paddingBottom:50,maxWidth:1400,width:'100%',alignSelf:'center'},hero:{backgroundColor:'#0B2743',borderRadius:22,padding:24,flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:20,marginBottom:20},heroCopy:{flex:1},eyebrow:{color:'#E6A84A',fontSize:11,fontWeight:'800',letterSpacing:2},title:{color:'#fff',fontSize:28,fontWeight:'800',marginVertical:6},description:{color:'#B9D3DF',fontSize:14,lineHeight:21,maxWidth:720},action:{backgroundColor:'#E6A84A',paddingHorizontal:18,paddingVertical:12,borderRadius:12},actionText:{color:'#071A2F',fontWeight:'800'},state:{backgroundColor:'#fff',borderRadius:18,padding:42,alignItems:'center',borderWidth:1,borderColor:'#E1DDD4'},stateTitle:{fontSize:18,fontWeight:'800',color:'#17324D',marginBottom:5},stateText:{color:'#718096',fontSize:13,marginTop:9,textAlign:'center'},emptyIcon:{fontSize:36,color:'#C88728'},error:{color:'#B42318',fontWeight:'700'},retry:{color:'#A66B1F',fontWeight:'800',marginTop:10},grid:{flexDirection:'row',flexWrap:'wrap',gap:14},card:{backgroundColor:'#fff',borderRadius:16,padding:18,minWidth:260,flex:1,borderWidth:1,borderColor:'#E1DDD4'},cardTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:12},cardTitle:{fontSize:15,fontWeight:'800',color:'#17324D',flex:1},cardBody:{color:'#60758A',fontSize:13,lineHeight:19,marginTop:12},badge:{backgroundColor:'#EAF4EF',borderRadius:20,paddingHorizontal:9,paddingVertical:4},badgeText:{fontSize:9,fontWeight:'800',color:'#287A54'}});
